# Generated by Django 3.1.7 on 2021-03-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Напишите вопрос')),
                ('question_image', models.ImageField(upload_to='', verbose_name='Загрузите картинку, Если есть необходимость')),
                ('answer1', models.BooleanField()),
                ('answer1_text', models.TextField(verbose_name='Первый ответ')),
                ('answer2', models.BooleanField()),
                ('answer2_text', models.TextField(verbose_name='Второе ответ')),
                ('answer3', models.BooleanField()),
                ('answer3_text', models.TextField(verbose_name='Третый ответ')),
                ('answer4', models.BooleanField()),
                ('answer4_text', models.TextField(verbose_name='Четвертый ответ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.category', verbose_name='Выберите категории')),
            ],
        ),
    ]
