# Generated by Django 3.1.7 on 2021-03-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='answer1',
            field=models.BooleanField(verbose_name='Отметьте правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='answer2',
            field=models.BooleanField(verbose_name='Отметьте правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='answer3',
            field=models.BooleanField(verbose_name='Отметьте правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='answer4',
            field=models.BooleanField(verbose_name='Отметьте правильный ответ'),
        ),
    ]
